config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'page/index'
  root to: 'page#index'

  get '/home', to: 'home#index'
  get '/hallo/:id', to: 'home#hallo'

  # get '/books', to: 'books#index'
  # get '/books/:id', to: 'books#show'
  # get '/books/new', to: 'books#new'
  # post '/books', to: 'books#create'
  # put '/books/:id', to: 'books#update'
  # delete '/books/:id', to: 'books#destroy'
  # create endpoint manually

  # create routing for books base on controller

  # generate routing only for some methods
  resources:books do
    get :active, on: :collection
    patch :toggle, on: :member
  end

  # resources:books,except :[:index,:show] => generate routing except for some methods on array except

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :page, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  has_rich_text :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
#index =>GET
    def index
        @books = Book.all
    end

#show =>GET
    def show
      @book = Book.find(params[:id])
    end

#new =>POST
    def new
        @book = Book.new
    end

#create =>POST
    def create
        @book = Book.new(resource_params)
        if @book.save
          redirect_to books_path, notice: "Berhasil menambah data buku"
        else
          render :new
        end
      end

#edit =>GET
    def edit
        @book = Book.find(params[:id])
    end

#update => Patch/Put
    def update
      @book = Book.find(params[:id])
      @book.update(resource_params)
      render plain: 'Berhasil mengubah data buku'
    end

#destroy => DELETE
    def destroy
      book = Book.find(params[:id])
     if book.destroy
      redirect_to books_path, notice: "Berhasil menghapus data buku"
      else
      redirect_to books_path, notice: "Gagal menghapus data buku"
     end
    end

    def active
      @books = Book.where(status: 1)
      render 'index'
    end

    def toggle
      @book = Book.find(params[:id])
      @book.status = !@book.status
      @book.save
      redirect_to books_path, notice: "Berhasil menonaktifkan buku"
    end

    private

    def resource_params
      params.require(:book).permit(:title, :page, :description)
    end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    # layout 'home_layout' => jika ingin mengeset layout untuk seluruh method
    def index
        # instance variable using @
        @langs = ['ruby','php','java','go','c++']
        @title = 'Hallo this is title'
        @books = Book.all
    end

    def hallo
      id = params[:id]
      book = Book.find_by(id:id)
      if book
        @title = book.title
      else
        @title = 'Book not found'
        end
    render layout: 'home_layout'
    end

    end

app/controllers/page_controller.rb
# create class page controller are def index
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/edit.html.erb
<%=form_for(@book) do |f|%>
    <div>
        <%=f.label :title%>
            <%=f.text_field :title%>
    </div>
    <div>
        <%=f.label :page%>
            <%=f.text_field :page%>
    </div>
    <div>
        <%=f.label :description%>
            <%=f.rich_text_area :description%>
    </div>
    <div>
        <%=f.submit 'data-turbo': false%>
    </div>
    <% end %>

app/views/books/index.html.erb
<%= link_to "New Book", new_book_path %>
<%= link_to "Active Book", active_books_path %>
<table border="1">
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Page</th>
    <th>Description</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= book.id %>
      </td>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.page %>
      </td>
      <td>
        <%= book.description %>
      </td>
      <td>
        <%= book.status %>
      </td>
      <td>
        <%= link_to "non_active",toggle_book_path(book.id),data:{turbo_method: :patch, turbo_confirm: "Are you sure"} %>
        <%= link_to "show",book_path(book) %>
        <%= link_to "edit", edit_book_path(book) %>
        <%= link_to "delete",book_path(book.id),data:{turbo_method: :delete, turbo_confirm: "Are you sure"} %>
      </td>
    </tr>
  <%end%>
</table>

app/views/books/new.html.erb
<%if @book.errors.any?%>
  <div>
    <% @book.errors.full_messages.each do |msg| %>
     <div><%= msg %></div>
    <% end %>
  </div>
<%end%>
<%=form_for(@book) do |f|%>
  <div>
    <%=f.label :title%>
    <%=f.text_field :title%>
  </div>
  <div>
    <%=f.label :page%>
    <%=f.text_field :page%>
  </div>
  <div>
    <%=f.label :description%>
    <%=f.rich_text_area :description%>
  </div>
  <div>
    <%=f.submit 'data-turbo': false%>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>
  <%=@book.title%>
</h1>

app/views/home/_information.html.erb
<h3>Informasi Produk terlaris</h3>

- <%=product_laris%>

app/views/home/hallo.html.erb
<h1>Hallo</h1>
<p>
    Hallo,
    <%= @title %>
</p>
<% content_for :menu do%>
    <p>Ini adalah menu</p>
<%end%>
<button id="btn-home">Click Me</button>

<%= render 'information',product_laris:@title%>

app/views/home/index.html.erb
<h1>Home</h1>
<%= render 'information',product_laris:@title%>
<ul>
    <% @langs.each do|lang| %>
        <li><%=lang%></li>
    <%end%>
</ul>
<h2><%=@title%></h2>

<table>
    <tr>
        <td>ID</td>
        <td>Title</td>
        <td>Description</td>
    </tr>
    <% @books.each do |book|%>
    <tr>
        <td><%=book.id%></td>
        <td><%=book.title%></td>
        <td><%=book.description%></td>
    </tr>
    <%end%>
</table>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Integrate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mono</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Layout Home Layout</h1>
    <%=yield :menu%>
    <%= yield %>
  </body>
</html>